//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CgroupSource) DeepCopyInto(out *CgroupSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CgroupSource.
func (in *CgroupSource) DeepCopy() *CgroupSource {
	if in == nil {
		return nil
	}
	out := new(CgroupSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerSource) DeepCopyInto(out *DockerSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerSource.
func (in *DockerSource) DeepCopy() *DockerSource {
	if in == nil {
		return nil
	}
	out := new(DockerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfig) DeepCopyInto(out *MetricsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfig.
func (in *MetricsConfig) DeepCopy() *MetricsConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromQLSource) DeepCopyInto(out *PromQLSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromQLSource.
func (in *PromQLSource) DeepCopy() *PromQLSource {
	if in == nil {
		return nil
	}
	out := new(PromQLSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePair) DeepCopyInto(out *ResourcePair) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePair.
func (in *ResourcePair) DeepCopy() *ResourcePair {
	if in == nil {
		return nil
	}
	out := new(ResourcePair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowWorkload) DeepCopyInto(out *ShadowWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowWorkload.
func (in *ShadowWorkload) DeepCopy() *ShadowWorkload {
	if in == nil {
		return nil
	}
	out := new(ShadowWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShadowWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowWorkloadList) DeepCopyInto(out *ShadowWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShadowWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowWorkloadList.
func (in *ShadowWorkloadList) DeepCopy() *ShadowWorkloadList {
	if in == nil {
		return nil
	}
	out := new(ShadowWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShadowWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowWorkloadSpec) DeepCopyInto(out *ShadowWorkloadSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.Metrics = in.Metrics
	in.Update.DeepCopyInto(&out.Update)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowWorkloadSpec.
func (in *ShadowWorkloadSpec) DeepCopy() *ShadowWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(ShadowWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowWorkloadStatus) DeepCopyInto(out *ShadowWorkloadStatus) {
	*out = *in
	out.CurrentCPU = in.CurrentCPU.DeepCopy()
	out.CurrentMemory = in.CurrentMemory.DeepCopy()
	in.LastResize.DeepCopyInto(&out.LastResize)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowWorkloadStatus.
func (in *ShadowWorkloadStatus) DeepCopy() *ShadowWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(ShadowWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerSource)
		**out = **in
	}
	if in.Cgroup != nil {
		in, out := &in.Cgroup, &out.Cgroup
		*out = new(CgroupSource)
		**out = **in
	}
	if in.Systemd != nil {
		in, out := &in.Systemd, &out.Systemd
		*out = new(SystemdSource)
		**out = **in
	}
	if in.PromQL != nil {
		in, out := &in.PromQL, &out.PromQL
		*out = new(PromQLSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSpec.
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemdSource) DeepCopyInto(out *SystemdSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemdSource.
func (in *SystemdSource) DeepCopy() *SystemdSource {
	if in == nil {
		return nil
	}
	out := new(SystemdSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicy) DeepCopyInto(out *UpdatePolicy) {
	*out = *in
	in.Floor.DeepCopyInto(&out.Floor)
	in.Ceiling.DeepCopyInto(&out.Ceiling)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicy.
func (in *UpdatePolicy) DeepCopy() *UpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicy)
	in.DeepCopyInto(out)
	return out
}
