apiVersion: v2
name: kube-symbiont
description: A Helm chart to distribute kube-symbiont
type: application

version: 0.1.0
appVersion: "0.1.0"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
